# Generated by Django 4.2.7 on 2023-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fila',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
    ]
