# Generated by Django 4.2.7 on 2023-11-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fila1',
            fields=[
                ('id1', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
