# Generated by Django 4.2.7 on 2023-11-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_padaria', '0002_fila1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fila1',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
